### ISSUE TITLE
Expiration date preventing preapproved sale close

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#108]
# Report

### What environment were you working in?
PRODUCTION

### What device were you using?
iPhone

### How severe is this issue?
MODERATE: should fix, but don't block next release

### What actually happened?
Went to fulfill the sale but it is saying that the sale is Expired/Failed

### What was the email (or phone number) for the account you were using?
sarah@agex.io

### What version of the app were you using?
2.18 (153)

### What actions did you take to try to make that happen?
I published a sale and was trying to fulfill it

### If you have any screenshots or recordings of the issue, please add the link(s) here.
https://docs.google.com/document/d/1hG3lyHurhPXip0jOBuY3dksBB8hPmKSo2WXujXBrKmU/edit?usp=sharing

### Email Address
sarah@agex.io

**Comment by joshpavlovich** [comment]
I have verified that is is not an issue in the Herd Android app.  It clears (nullify) the expiration date/time when the user selects yes for the pre-approved buyer question and the expiration date has a previous value.
