### ISSUE TITLE
NextButton stays enabled in section change

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#166]
# Bug Report

### If you have any screenshots or recordings of the issue, please add the link(s) here.
https://drive.google.com/open?id=1ZbEarM_5TlytMXIj2krWepx3E96y-rBH

### What actually happened?
On initial viewing of Logistics - step 4 the Next button appeared active. When trying to click on the active next button it changed to inactive and required the selection of an address before changing to active again.

The next button should not be active until the user selects and address. 

**Note:**
This happens when the user changes to the net section using the menu selector and not clicking in the next button.

# Affected Repositories
- [ ] agex.admin
- [ ] agex.api
- [ ] agex.common
- [ ] agex.service_workers
- [ ] agex.web
- [ ] android.herd
- [X] ios.herd

**Comment by eharo2** [comment]
Issue moved to [agex-inc/ios.herd #573](https://github.com/agex-inc/ios.herd/issues/573) via [**ZenHub**](https://www.zenhub.com/)
