### ISSUE TITLE
Skip sale wizard logistics for preapproved sales

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#170]
# Report

### Give us a short description of the new feature

Remove 'Origin Location' for predetermined buyer in sales.

### Current Behavior:  How do things work now?
Origin location is required to complete a predetermined sale for an owner.  This also requires that an owner have a location of ANY sort simply to do a sale.  

### What part of the system needs work?
Herd

### User Narrative(s):  What kind of user(s) need this feature?  Why do they want it?
As a User, for sales that already have predetermined trade terms, I want to skip the origin location as this does not matter for a sale at that point; the deal has already been made

### Is this a bug or a new feature request?
Feature (I can't do something I want to do)

### Timestamp
3/25/2020 22:20:03

### Email Address
blakew@agex.io

### Desired Behavior:  What would be nice to change if we have time?
Skip Step 4 altogether for predetermind buyer sales; assumes that all sales are immediate delivery and that transport distance is not needed (largely unused feature).  User can always edit from Step 6 if need be.   

### Required Behavior:  What has to change for this to be "done"?
Remove location requirement for predetermined Buyer sales.

**Comment by altemeier** [comment]
I recall agreeing with Blake that we would skip the Logistics section for pre-approved buyers.  I assume that's what he intended to document with this ticket.

**Comment by eharo2** [comment]
✅
