### ISSUE TITLE
Allow hot weight and cold weight to be removed/cleared (nullified)

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#172]
# Report

### How severe is this issue?
LOW: would be nice to fix when we can

### What was the email (or phone number) for the account you were using?
salt+packer@agex.io

### What device were you using?
Multiple

### What part of the system needs work?
Packer

### What actually happened?
The apps let me empty the fields and save the animal, but the hot and cold weights were not actually nullified.

### Were you using a "native" or "web" app?
Native (downloaded from a store)

### What were you generally trying to do?
remove hot/cold weight

### What actions did you take to try to make that happen?
empty the fields, save the animal

### In what screen/page did you find the bug?
Packer > Animal Detail

### What version of the app were you using?
iOS 156, Android 21001

### What environment were you working in?
TEST

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### Timestamp
3/26/2020 15:12:38

### Is this bug also in the DEMO and/or PRODUCTION environments?
Yes, the bug also occurs in DEMO and/or PRODUCTION

### Email Address
salt@agex.io

# Affected Repositories
- [ ] agex.admin
- [ ] agex.api
- [ ] agex.common
- [ ] agex.service_workers
- [ ] agex.web
- [x] android.herd
- [x] ios.herd

**Comment by eharo2** [comment]
✅
