### ISSUE TITLE
Dynamically query for pre-approved buyer editing a sale on the 'Auction details" screen

### ISSUE THREAD

**Issue by joshpavlovich** [agex-inc/support.requests#178]
## User Narrative(s)
_As an affiliate, I want to dynamically for query pre-approved buyers when I type so that I am assured that I will be able to select a newly added buyer to the platform._

## Current Behavior
1. Buyers are only fetched when the app is first launched from a 'cold' start and the buyers are queried from the local database.

## Acceptance Criteria
1. Fetch pre-approved buyers for a sale on the 'Auction details" screen, similar to how we select owners in consignment.
2. The pre approved buyer auto complete view should do a full text search against the user endpoint by any user attribute (i.e., first name, last name, email, phone, etc) and return a list of users for selection.
3. The user must enter at least 3 characters, before a request is made to the API.
4. The app should try to cache previous results in the view state, so that fewer requests are made to the API (similar to consignment). 
5. Fetching pre-approved buyers will require internet connectivity and we will need to handle http errors by giving the user feedback if there is a connectivity error.

**Comment by altemeier** [comment]
A few suggestions to make these requests as quick/efficient as possible:

1. **DO NOT** add `expand` or `expanded` query parameters.  Fetching expanding results is significantly slower and unnecessary here.
2. **DO NOT** add a large `size` parameter to these requests (in some requests we put `size=5000`).  The default `size` is 25, which should be more than enough to display to the user.
3. **DO** use a single `q` query parameter in the request; **DO NOT** add multiple parameters for different properties with the same value.  There are a few reasons for this:
    1.  The API considers multiple query parameters to be a _conjunctive_ filter request.  This means that if you add parameters for both `email` and `phone` in the same request, the API will only return results that match on **_both_** of those fields.  Since no user has the same `phone` as `email`, this request will always return zero results.    
    2. The API currently validates query parameters for `email` and `phone`.  This means that a partial entry will return a 400 error because it is not the right format.
    3. For search requests, the API adds a helpful `_highlight` property to each result.
        1. This property is generated by elasticsearch, and indicates which fields matched.
        2. The value of this property is an object/map/dictionary.  The keys of this object are the properties that matched.  The value of each key is an array of html strings, with the matching portions of the relevant property emphasized.
        3. Clients can use this property in two ways:
            1. To filter out results that did not match on the properties we care about
            2. To display the matching portion of each object to the user (if we want).
        4. As an example, a search in production against the `/user` resource with `q=salt@agex.io owner` returns this as the first result:
```
{
  "email": "salt+buyer@agex.io",
  "groups": [
    "owner"
  ],
  "id": "443c1302-0069-426b-bd0f-6cc16cd7cdb4",
  [other user properties omitted],
  "_highlight": {
    "groups": [
      "<em>owner</em>"
    ],
    "email": [
      "<em>salt</em>+buyer@<em>agex.io</em>"
    ]
  }
}
```

This suggestion applies to any "full text search" context (like consignment), where a single field is designed to search against multiple properties.

In the future, it could also be used to enhance the animals search bar when the user has a network connection.

**Comment by altemeier** [comment]
:white_check_mark:
