### ISSUE TITLE
Provide a way to refresh owners from within the app

### ISSUE THREAD

**Issue by joshpavlovich** [agex-inc/support.requests#179]
## User Narrative(s)
_As an affiliate, I want to the app to refresh my owners dynamically so that I am assured that I will be able to select a newly added/associated owner._

## Current Behavior
1. An operator must log out and back in or close and re-launch the app to see newly added owners

## Acceptance Criteria
1. Refresh a user's data and associated owners when the navigation drawer is opened by the user.
2. Populate the owner's selection dropdown with the updated owners for the affiliate from the API.

# ***ORIGINAL FEATURE REQUEST BELOW***

# Report

### User Narrative(s):  What kind of user(s) need this feature?  Why do they want it?
Stockyard operators

### Is this a bug or a new feature request?
Feature (I can't do something I want to do)

### Timestamp
3/27/2020 13:29:58

### Email Address
salt@agex.io

### Required Behavior:  What has to change for this to be "done"?
Some mechanism to refresh "owners" from within the app.

### Give us a short description of the new feature
Refresh relevant owners without logging out.

### Current Behavior:  How do things work now?
An operator must log out and back in or close and re-launch the app to see newly added owners

### What part of the system needs work?
Herd

**Comment by eharo2** [comment]
✅
