### ISSUE TITLE
Enable nullification of address_line_1

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#19]
# Report

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### What environment were you working in?
TEST

### What device were you using?
iPhone

### How severe is this issue?
LOW: would be nice to fix when we can

### Timestamp
2/28/2020 10:53:50

### In what screen/page did you find the bug?
edit location

### What actually happened?
Completely removing the street value in location edit doesn't update the location as expected.

### What part of the system needs work?
General/Other

### Were you using a "native" or "web" app?
Native (downloaded from a store)

### What was the email (or phone number) for the account you were using?
jjohnson@agex.io

### What were you generally trying to do?
edit location, remove street name from location

### What version of the app were you using?
154

### If you have any screenshots or recordings of the issue, please add the link(s) here.
https://drive.google.com/file/d/1ma8Rv4X1NtC2K1yanRn1z9g5_21Pi7AL/view

### Email Address
jjohnson@agex.io

@joshpavlovich commented on [Fri Jan 31 2020](https://github.com/agex-inc/android.herd/issues/434)

**Comment by altemeier** [comment]
API: Fixed in https://github.com/agex-inc/agex.api/commit/7c06d9bae117c0b7cc8b2a05e0fdcc4e1aa76f0c

**Comment by joshpavlovich** [comment]
android.herd: Fixed in [android.herd/434](https://github.com/agex-inc/android.herd/issues/434) which is in Review/QA.
