### ISSUE TITLE
Consigned animals from another client are not removed when all of the owner's animals are consigned 

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#226]
# Report

### What was the email (or phone number) for the account you were using?
new+stockyard@agex.io

### What part of the system needs work?
Herd

### What actually happened?
Consigned all the owner's animals from another client.  When refreshing the consigned animals are not removed. However, they are removed when the owner has new animal(s) on the next refresh. 

### Were you using a "native" or "web" app?
Native (downloaded from a store)

### What were you generally trying to do?
Animals list when refreshing animals

### What actions did you take to try to make that happen?
Refresh the animals list after consigning from another client and then verify that the animals are removed from the selected owner on mobile app.

### What version of the app were you using?
21200

### What environment were you working in?
TEST

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### Timestamp
4/23/2020 15:24:49

### Is this bug also in the DEMO and/or PRODUCTION environments?
Yes, the bug also occurs in DEMO and/or PRODUCTION

### Email Address
josh@agex.io

### How severe is this issue?
MODERATE: should fix, but don't block next release

**Comment by joshpavlovich** [comment]
Issue moved to [agex-inc/android.herd #494](https://github.com/agex-inc/android.herd/issues/494) via [**ZenHub**](https://www.zenhub.com/)
