### ISSUE TITLE
Use of iOS 13 specific TextFieldDelegate is limiting OS Support

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#264]
# Report

### What device were you using?
iPhone

### What was the email (or phone number) for the account you were using?
a1@agex.io

### Were you using a "native" or "web" app?
Native (downloaded from a store)

### What actually happened?
The sales wizard is failing to update properties in a sale object due to the usage of a new iOS 13 function to detect changes in the input.  

Workaround is to upgrade the iPhone to iOS 13, but his drastically limits the OS version support, given that iOS 10.3 and up are supported throughout the app. 

### What part of the system needs work?
Herd

### How severe is this issue?
CRITICAL: must fix before next release

### Is this bug also in the DEMO and/or PRODUCTION environments?
Yes, the bug also occurs in DEMO and/or PRODUCTION

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### What environment were you working in?
TEST

### What version of the app were you using?
Any

### Timestamp
5/21/2020 13:39:46

### Email Address
enrique@agex.io

**Comment by eharo2** [comment]
Issue moved to [agex-inc/ios.herd #647](https://github.com/agex-inc/ios.herd/issues/647) via [**ZenHub**](https://www.zenhub.com/)
