### ISSUE TITLE
Consigned Animals not being transferred  when completing a sale

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#274]
# Report

### Timestamp
6/2/2020 20:01:12

### If you were using the web, what browser were you using?
Chrome

### What part of the system needs work?
Herd

### What were you generally trying to do?
Transfer animals after sale with consigned group

### Is this bug also in the DEMO and/or PRODUCTION environments?
No, the bug only occurs in DEV and/or TEST

### What environment were you working in?
TEST

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### What device were you using?
Laptop/desktop computer

### What was the email (or phone number) for the account you were using?
a63@agex.io

### Were you using a "native" or "web" app?
Web (using a web browser)

### What actions did you take to try to make that happen?
1- I created new users in the web (all new accounts also got a Location):
- o63@agex.io  (Owner.Web Jun.3)
- b63@agex.io (Buyer.Web Jun.3)
- a63@agex.io (Affiliate.Web Jun.3)

2- Added all relationships in ADMIN

3 - 
- Logged as the affiliate, selected the owner account. 
- I created a new group, and added 4 new animals (manually). 
- Consigned the animals to self (affiliate) and switched to the affiliate account

4 - I then switched to the mobile App.  - Created a sale with pre-approved buyer (new buyer account) and fulfilled the sale

5 - In Admin i transferred the animals. The system reports 4 animals transferred

In the affiliate account, the consigned group is removed, but the animals are not transferred to the buyer account.

![image.png](https://images.zenhubusercontent.com/5ae35ff84b5806bc2bd0f02d/f36b5cd4-e4ff-4441-b6e6-c75240b71a23)

I completed the process twice, using iOS and Android to create/fulfill the sale.  In both cases, the animals were not transferred

Sales in TEST are:
22798aeb-7358-405d-ba1c-4d8f2620dc98
98adb24b-796d-468e-a3ee-2bf174b7e1f4

### Email Address
enrique@agex.io

### In what screen/page did you find the bug?
StockYard Flow

### What version of the app were you using?
2020.06.01

**Comment by joshpavlovich** [comment]
FYI, I did 5 of the describe above stockyard operator sales and all of the animals were properly transferred to the pre-approved buyer.

**Comment by altemeier** [comment]
Closing this per discussion and additional review.
