### ISSUE TITLE
"Use current location" button must be presed twice after authorizing access

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#280]
# Report

### Bug Report?
Add Location - The location form did not populate after I accepted permissions.  I had to press “use current location” again.

### What actions did you take to try to make that happen?
I was asked to give location permission to the app.  I accepted.

### Acceptance Criteria
After accepting permissions, the form should be populated if the location is found.

**Comment by eharo2** [comment]
Issue moved to [agex-inc/ios.herd #666](https://github.com/agex-inc/ios.herd/issues/666) via [**ZenHub**](https://www.zenhub.com/)
