### ISSUE TITLE
Find animal by AGEX plastic tag

### ISSUE THREAD

**Issue by joshpavlovich** [agex-inc/support.requests#291]
Notes: Animals can be fetched by their id and tag_number.

If the current user is in the packer user group, include a packer_fetch=true query parameter in the url to create an animal for the provided animal identifier if it does not already exist.This prevents packer users from receiving an HTTP 404 error if the animal does not exist.

See, https://agex.docs.apiary.io/#reference/animal/animal/retrieve-animal

**Comment by eharo2** [comment]
@altemeier @joshpavlovich   Moving the discussion to the ticket.      My question re: fetching an animal using the paper tag is considering the scenario, when the user has a carcass that has an agex-tempraty tag, but not an agex-durable tag,  and wants to update deductions.
