### ISSUE TITLE
Add new basic animal packer properties

### ISSUE THREAD

**Issue by joshpavlovich** [agex-inc/support.requests#295]
## User Narrative(s)
_As a packer user, I want to add additional details the animal, so that the carcass will have all recorded data to share with the producer and determine the final price._

## Current Behavior
1. Packer users can only add/edit hot weight, cold weight, quality grade, yield grade, and deductions.

## Acceptance Criteria
1. Add new basic editable fields listed in [the concept document](https://docs.google.com/document/d/1cpoky3lGPn5Ymf1VCsf530lthMb-r7BjVWxIYtdjcn0/edit#heading=h.ux2ibpbcjm52)

![Screen Shot 2020-08-31 at 11.35.44 AM.png](https://images.zenhubusercontent.com/5948213351aa2c3057821eb9/f34a7fec-364b-41df-8148-a40908168dc1)

**Comment by eharo2** [comment]
@altemeier @joshpavlovich These 3 fields (live weight, color and sex) should display any of the properties from the animal object (if they exist) and are editable, but not required.    Is that correct?

**Comment by joshpavlovich** [comment]
> @altemeier @joshpavlovich These 3 fields (live weight, color and sex) should display any of the properties from the animal object (if they exist) and are editable, but not required. Is that correct?

@eharo2 Yes, they are editable and not required 👍
