### ISSUE TITLE
Consign View Dialog not dismissed when the consignment fails

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#311]
# Report

### What version of the app were you using?
173

### How severe is this issue?
MODERATE: should fix, but don't block next release

### What device were you using?
iPhone

### Email Address
enrique@agex.io

### Timestamp
6/29/2020 12:17:28

### What environment were you working in?
DEV

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### Were you using a "native" or "web" app?
Native (downloaded from a store)

### Is this bug also in the DEMO and/or PRODUCTION environments?
Yes, the bug also occurs in DEMO and/or PRODUCTION

### What actually happened?
The Consign Dialog View is not dismissed when the consignment fails

### In what screen/page did you find the bug?
Consign View

### What was the email (or phone number) for the account you were using?
a71@agex.io

### What part of the system needs work?
Herd

**Comment by eharo2** [comment]
Issue moved to [agex-inc/ios.herd #691](https://github.com/agex-inc/ios.herd/issues/691) via [**ZenHub**](https://www.zenhub.com/)
