### ISSUE TITLE
Add multiple alternate tags to a packer animal

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#319]
## User Narrative(s)
_As a packer user, I want to add more than one non-AGEX physical IDs for an animal, so that the packing plant can record any identifiers on the animal._

## Current Behavior
1. Packer users can only add one AGEX durable tags and a single carcass id to track the carcass.
2. Users can only add one `alternate_tag` per animal.

### API Behavior
1. A the new `alternate_tags` [collection attribute](https://agex.docs.apiary.io/#introduction/collection-attributes) to the Animal entity
2. The API ensures the old `alternate_tag` property contains the most recently added alternate tag
3. When a user adds or updates the `alternate_tag` property, the API adds the new value to the `alternate_tags` array
4. If a user removes values from `alternate_tags` without adding other `alternate_tags`, the API nullifies the `alternate_tag` field if it is currently set to one of the removed values

### Mobile App Behavior
1. The edit packer animal screen should indicate the number of alternate tag attached to the animal.
2. The edit packer animal screen should allow users to add a new alternate tag.
3. _The edit packer animal screen may allow editing and removing alternate tags in the future.  This could be similar to the Herd edit animal UX for `notes_complex`._

**Comment by eharo2** [comment]
@altemeier , @joshpavlovich     This is the new proposal for alt tags...   
- Simple input of the next alternate_tag to add
- An indicator of the total number of alternate_tags in the animal
- The 'total' can also be a button to show the list of alternate_tags in case they need to be inspected or removed.
- It keeps consistency with the paperTags UI.
- It also allows for the scan button to be used for scanning other types (e.g. Barcodes).    i.e.   If the scanned tag is non AGEX (platic or paper) the value populates the 'alternate_tag' field

Comments or suggestions welcome....   e

![image.png](https://images.zenhubusercontent.com/5ae35ff84b5806bc2bd0f02d/90a0ef8d-b98b-4e86-b598-34e8ada16120)

**Comment by joshpavlovich** [comment]
### The proposal for adding multiple alternate tags to a packer animal will have the following screen elements:

- A label of "Alternate tags:" and the count displayed using bold text.
- An add alternate tag button to the right edge of the screen aligned with the alternate tag label and value in a row.
- The add alternate tag button uses the [Material Design "add" icon](https://material.io/resources/icons/?search=add&icon=add&style=outline).
- The add alternate tag button has a tooltip, "Add alternate tag", when it is long pressed.
- When clicking on the add alternate tag button, a dialog is shown with a title of "Add alternate tag?" and an edit text allowing the user to enter a new alternate tag.
- The dialog has a positive button of "Add" and a negative button of "Cancel". 
- The "Add" button is disabled until the user enters at least one character of the alternate tag.
- When the user taps the "Add" button the alternate is added to the animal to be saved and the alternate tags count is incremented.

### Below are the screenshots for the proposal to add multiple alternate tags to the edit packer animal screen:

#### This screenshot shows a packer animal with zero alternate tags.  
![device-2020-08-27-180438](https://user-images.githubusercontent.com/923509/91503504-404dda00-e890-11ea-9078-df932f9ea5f5.png)

#### This screenshot shows a tooltip, "Add alternate tag", when the add alternate tag is long pressed.
![device-2020-08-27-195136](https://user-images.githubusercontent.com/923509/91509042-ca04a400-e89e-11ea-9b22-bd5b5beac560.png)

#### This screenshot shows the add alternate tag dialog with no alternate tag entered and the "Add" button disabled.
![device-2020-08-27-180546](https://user-images.githubusercontent.com/923509/91503509-42179d80-e890-11ea-9b39-b1d968d69a38.png)

#### This screenshot shows the add alternate tag dialog with an alternate tag entered ("Red 25") and the "Add" button enabled.
![device-2020-08-27-180601](https://user-images.githubusercontent.com/923509/91503510-42b03400-e890-11ea-9f76-2e159e3e81e6.png)

#### This screenshot shows the alternate tag count incremented to "1" after a tag is added from the previous screenshot.
![device-2020-08-27-180617](https://user-images.githubusercontent.com/923509/91503511-4348ca80-e890-11ea-8ca9-64f2824f2ac7.png)

#### This screenshot shows the add alternate tag dialog with another alternate tag entered ("Red 26") and the "Add" button enabled.
![device-2020-08-27-180643](https://user-images.githubusercontent.com/923509/91503512-4348ca80-e890-11ea-9575-667a6a1bce76.png)

#### This screenshot shows the alternate tag count incremented to "2" after a tag is added from the previous screenshot.
![device-2020-08-27-180658](https://user-images.githubusercontent.com/923509/91503514-43e16100-e890-11ea-97d5-ff92b06b7dd9.png)

**Comment by joshpavlovich** [comment]
Here is a screen record, [Packer Add Alternate Tags Proposal](https://drive.google.com/open?id=19fXudJdHn8JDvT3k9ut0U8LUxpq5U7iv), that shows the alternate tags proposal when editing a packer animal...
