### ISSUE TITLE
Add paper tags support to edit packer animal

### ISSUE THREAD

**Issue by joshpavlovich** [agex-inc/support.requests#329]
## User Narrative(s)
_As a packer user, I want to add multiple temporary paper tags to the carcass, so that the packing plant can track the whole animal when it is split in half or quarters._

## Current Behavior
1. Packer users can only add one AGEX durable tags and a single carcass id to track the carcass.

## Acceptance Criteria

**Physical Attributes**
1. Paper tag numbers are formatted exactly like plastic tags, except they begin with a `3` instead of a `2`.
2. Each paper tag has a visually scannable QR encoded with a globally unique tag number.
3. Paper tags need not display any human-readable ID.

**UI/UX**
1. Users can add multiple paper AGEX tags to each animal by scanning the paper tag's QR code on the edit packer animal screen.
2. Users cannot remove paper tags.
3. Users cannot "transfer" paper tags from one animal to another.
3. Users can only see how many paper tags are attached to an animal on the edit packer animal screen; they cannot see the particular tag numbers.

**Comment by joshpavlovich** [comment]
### Below are the final 2 proposals for the "Paper tags" label and count: 

#### 1. The first one has a label of "Paper tags" and the count displayed in the app's primary text color with a light grey circle background.
![device-2020-08-25-110112](https://user-images.githubusercontent.com/923509/91473914-2ba51e00-e85f-11ea-890a-19322ee0dfd5.png)

#### 2. The second one has a label of "Paper tags:" and the count displayed using bold text.
![device-2020-08-25-111739](https://user-images.githubusercontent.com/923509/91473932-32cc2c00-e85f-11ea-9a15-ac6b19f31569.png)

**Comment by altemeier** [comment]
Thanks @joshpavlovich and @eharo2 for a good discussion on this.

Let's use option #2 above.
