### ISSUE TITLE
App crashes at Packer Logou

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#342]
# Report

### Is this bug also in the DEMO and/or PRODUCTION environments?
Yes, the bug also occurs in DEMO and/or PRODUCTION

### What version of the app were you using?
Build 181

### How severe is this issue?
CRITICAL: must fix before next release

### What actually happened?
Crash at Packer Logout

### Acceptance Criteria
The user can logout from Packer as expected

**Comment by eharo2** [comment]
Issue moved to [agex-inc/ios.herd #748](https://github.com/agex-inc/ios.herd/issues/748) via [**ZenHub**](https://www.zenhub.com/)
