### ISSUE TITLE
Can't add/edit Animals in Herd

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#344]
# Report
### What actions did you take to try to make that happen?
added an animal via an AGEX tag.  subsequently edited the animal, adding breed, gender, a note, and one photo.

### How severe is this issue?
CRITICAL: must fix before next release

### Acceptance Criteria
Animal add/edit should work as expected, including first note, notes and pics

**Comment by eharo2** [comment]
Issue moved to [agex-inc/ios.herd #752](https://github.com/agex-inc/ios.herd/issues/752) via [**ZenHub**](https://www.zenhub.com/)
