### ISSUE TITLE
Realm 'Invalid Object' Crash in Group Detail View

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#350]
# Report

### What were you generally trying to do?
User was accessing the Groups Detail View

### In what screen/page did you find the bug?
Chraslytics

### What environment were you working in?
PRODUCTION

### What device were you using?
iPhone

### Email Address
enrique@agex.io

### What part of the system needs work?
Herd

### What version of the app were you using?
v2.26 9179)

### Were you using a "native" or "web" app?
Native (downloaded from a store)

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### Timestamp
8/20/2020 20:30:24

### How severe is this issue?
CRITICAL: must fix before next release

### What was the email (or phone number) for the account you were using?
enrique@agex.io

**Comment by eharo2** [comment]
Issue moved to [agex-inc/ios.herd #760](https://github.com/agex-inc/ios.herd/issues/760) via [**ZenHub**](https://www.zenhub.com/)
