### ISSUE TITLE
iOS Packer can't pair with RFID gun 2nd time

### ISSUE THREAD

**Issue by brothhammer** [agex-inc/support.requests#358]
## User Narrative(s)
As a packer user, I want to be able to reconnect to the RFID gun so that I can scan tags.

## Current Behavior
1.) After connecting to the RFID gun the first time the "Connected to RFID" button is still active. If this is clicked the app no longer recognizes the RFID gun even though it is still connected to the phone. No combination of logging out or powering down the gun allowed the app to reconnect. No work around was found.

## Steps to Reproduce
1.) Log into app version 191 as a packer for the first time
2.) The RFID gun was off and not connected to the iPhone
3.) Login success and presented with the empty select device list
4.) Pull the trigger to turn on the RFID gun
5.) Select the RFID gun from the list when it appears
6.) The gun connects and is usable (everything as it should be up to here)
7.) The button at the top reads “Connected to Reader” but is still an active button
8.) Clicking the “Connected to Reader” button leaves the RFID gun connected to the iPhone (based on the solid blue LED on the gun) but the app no longer thinks the gun is connected.
9.) Remove the battery from the gun to force a disconnect
10.) Log out and log back in
11.) Was not presented with the device list like the first time
12.) The button now reads “Connect to Reader” but it does not work

## Acceptance Criteria
1. Packer user must be able to establish viable connection with RFID gun from any state.
Some options to think about
1. Disable the button - should result in the RFID gun staying connected and recognized but limits the ability to switch guns if need be
2. Make the button formally disconnect the RFID gun from the phone and app. This is more robust and should allow the user to switch devices if they need to

## Related Documents/Videos/Links
1.

**Comment by eharo2** [comment]
Issue moved to [agex-inc/ios.herd #767](https://github.com/agex-inc/ios.herd/issues/767) via [**ZenHub**](https://www.zenhub.com/)
