### ISSUE TITLE
The SIGNUP Button is enabled with an incorrect email

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#361]
# Report

### What part of the system needs work?
Herd

### Is this bug also in the DEMO and/or PRODUCTION environments?
No, the bug only occurs in DEV and/or TEST

### Timestamp
9/8/2020 14:06:21

### What version of the app were you using?
v2.28 (193) 

### How severe is this issue?
MODERATE: should fix, but don't block next release

### Were you using a "native" or "web" app?
Native (downloaded from a store)

### Email Address
enrique@agex.io

### What environment were you working in?
TEST

### What actions did you take to try to make that happen?
Entered an invalid email

### What device were you using?
iPhone

### In what screen/page did you find the bug?
Signup

### What were you generally trying to do?
Signup

### What actually happened?
The textfield shows the correct warning, but the SIGNUP button is enabled when T&C are accepted, resulting in a BAD REQUEST.

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### What was the email (or phone number) for the account you were using?
enrique@agex.io

**Comment by eharo2** [comment]
Issue moved to [agex-inc/ios.herd #780](https://github.com/agex-inc/ios.herd/issues/780) via [**ZenHub**](https://www.zenhub.com/)
