### ISSUE TITLE
Table not updated when adding an animal OFFLINE

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#362]
# Report

### What environment were you working in?
TEST

### Email Address
enrique@agex.io

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### Timestamp
9/8/2020 14:10:42

### What part of the system needs work?
Herd

### What device were you using?
iPhone

### How severe is this issue?
MODERATE: should fix, but don't block next release

### In what screen/page did you find the bug?
Add animals

### Is this bug also in the DEMO and/or PRODUCTION environments?
No, the bug only occurs in DEV and/or TEST

### What was the email (or phone number) for the account you were using?
p98@agex.io

### What were you generally trying to do?
Add animals OFFLINE

### What version of the app were you using?
v2.28 (193)

### What actually happened?
The table is not updated showing the added animal, until pull to refresh is executed.   If a note is added to the animal, it is not shown until the user is back online.     No impact to user info

### Were you using a "native" or "web" app?
Native (downloaded from a store)

### What actions did you take to try to make that happen?
Adde one animal online

**Comment by eharo2** [comment]
Issue moved to [agex-inc/ios.herd #781](https://github.com/agex-inc/ios.herd/issues/781) via [**ZenHub**](https://www.zenhub.com/)
