### ISSUE TITLE
Create a new lot when editing a packer animal

### ISSUE THREAD

**Issue by joshpavlovich** [agex-inc/support.requests#370]
## User Narrative(s)
_As a packer user, I want to create a new lot when editing an animal/carcass and the current lot is not available for selection, so that the packer can associate it with the correct producer._

## Current Behavior
1. There is no way to create a new lot when editing a packer animal.

## Acceptance Criteria
1. On the edit packer animal screen, the user should be able create a new basic lot.
2. In the lots dropdown, the last item should be an actionable item "Add new lot", to increase the chances users see all their existing options before creating a new one.
2. When the user taps on the "Add new lot" item in the lots dropdown, then show the user a simple form to enter basic lot info; name (required) and description.
3. The kill date that will be derived from the current animal's kill date.
• If the animal has a kill date, then set the lineup's kill date the animal's kill date.
• If the animal does not have a kill date, then set the lineup's kill date to the current date (UTC).
4. On the basic lot creation form when the user taps "Save" the following will be executed: 
	* the lot is created and persisted to the API
	* the lot is added to the available lots on the edit packer animal screen
	* the lot is selected on the edit packer animal screen
5. On the basic lot creation form when the user cancels creating a new lot the form is closed and the edit packer animal is displayed.

**Comment by joshpavlovich** [comment]
## Please see the proposed UI for creating a new lot from the edit packer animal screen

### This is a screenshot of the the edit packer animal screen with the lots dropdown having a last item "Add new lot" 
![device-2020-10-02-130151](https://user-images.githubusercontent.com/923509/94954996-801b6900-04af-11eb-9eba-30b781abbcae.png)


### This is a screenshot for the add lot (basic) screen
![device-2020-10-01-180804](https://user-images.githubusercontent.com/923509/94872574-8c9db400-0412-11eb-8cca-949a90f34230.png)
![device-2020-10-01-180901](https://user-images.githubusercontent.com/923509/94872584-96271c00-0412-11eb-80bd-e0bc3eba7665.png)

**Comment by altemeier** [comment]
Would it be difficult to include "create lot" as an option in the lots dropdown, instead of to the side?  My concern is users creating many versions of the same lot without checking the available lots first...

**Comment by joshpavlovich** [comment]
Here is the questions and answers from a Slack conversation I had with @altemeier this morning regarding the create lot option:

**_josh  10:26 AM_**
Here are a few questions I have before we investigate making the change:

1. Should the create lot action item be the first item in the dropdown? 
2. Should the text be "Create lot" or something else..."Add new lot"?
3. Do we need the "None" selection item? 

**_salt  10:28 AM_**
Good questions.  My goal is to prevent users from carelessly selecting an incorrect lot or duplicating lots.  
With that in mind:

1. I would put the create lot action item last, to increase the chances users see all their existing options before creating a new one
2. I like "Add new lot"
3. I think so, to ensure users affirmatively select a lot

I have updated the ticket's acceptance criteria and the proposed UI screenshots.

**Comment by eharo2** [comment]
I just made a change to fix a typo in the Acceptance Criteria,  point 6:    `the **user** cancels`
