### ISSUE TITLE
Allow herd app users to link to "AGEX Marketplace"

### ISSUE THREAD

**Issue by joshpavlovich** [agex-inc/support.requests#371]
## User Narrative(s)
_As an owner, I want be able list my animals for sale, so that buyers can contact me to purchase the animals._

## Current Behavior
1. Owners using the Herd mobile app cannot list their animals for sale.

## Acceptance Criteria
1. Add a "Sales" item after "Locations", to the bottom navigation bar.
2. When the user selects "Sales", show them a basic screen introducing the "AGEX Marketplace" with the following description: "Herd owners can now market their own cattle on AGEX!  Visit the AGEX marketplace to view current sales, or create your own."
3. Underneath the description is a button with the label "Visit Marketplace" that links the user to https://app.agex.io/marketplace.
4. There is no floating action button on the "Sales" page.

**Comment by joshpavlovich** [comment]
![device-2020-09-16-141408](https://user-images.githubusercontent.com/923509/93381910-f6b93500-f826-11ea-907c-94838e8d85e9.png)

**Comment by brothhammer** [comment]
:white_check_mark:
