### ISSUE TITLE
Apply a lot to a packer animal

### ISSUE THREAD

**Issue by joshpavlovich** [agex-inc/support.requests#385]
## User Narrative(s)
_As a packer user, I want to apply the current lot to the animal/carcass so that the packer can associate it with the correct producer._

## Current Behavior
1. There is no way to associate the animals to a producer when editing a packer animal.

## Acceptance Criteria
1. On the edit packer animal screen, the user should be able to select a lot and apply the selected lot when the animal is saved.
2. The user should be able to select a lot based on the kill date set on the animal.
• If the animal has a kill date, then fetch lineups from the API equal to the kill date (UTC) for the packer.
• If the animal does not have a kill date, then fetch lineups from the API equal to the current date (UTC) for the packer.
3. The lot selections should be formatted using the lot name and kill date (i.e., "Lot #1 - Sep 28, 2020") and ordered by kill date and name.
4. Lot is a required field. Show a required field message when the a lot selection is not made and the user attempts to save the animal.
5. On the edit packer animal screen, if the animal has an existing lot applied, then the lot should be selected when the animal is displayed.
6. The user should be able to change the lot and apply the selected lot when the animal is saved.
7. If the user changes the kill date, then fetch lineups from the API equal to the new kill date (UTC) for the packer to populate the lot selection dropdown, clear the lot selection and require a new lot selection to save the animal.

**Comment by joshpavlovich** [comment]
## Please see the proposed UI for the lot selection on the edit packer animal screen

### This is a screenshot for when the animal has no lot value is selected
![Screenshot_1601333216](https://user-images.githubusercontent.com/923509/94493642-bf497180-01b2-11eb-966e-31c99382265a.png)

### This is a screenshot showing the values available for selection
![Screenshot_1601333220](https://user-images.githubusercontent.com/923509/94493667-cf615100-01b2-11eb-8449-9e84e03b535a.png)


### This is a screenshot for when the animal has a lot value is selected
![Screenshot_1601333227](https://user-images.githubusercontent.com/923509/94493685-db4d1300-01b2-11eb-8842-0f2d94599d19.png)

**Comment by altemeier** [comment]
Looks great to me 👍

**Comment by eharo2** [comment]
@joshpavlovich @altemeier 
Is the Lot required to save the animal?    i.e.No lots for that `kill_date` were fetched, and the user does not create a new one....     Should the user be able to save the animal?             i don't know what common would it be to process an animal that is not part of a lot
