### ISSUE TITLE
Animal created without tag

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#54]
# Report

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### What environment were you working in?
TEST

### What device were you using?
Laptop/desktop computer

### If you were using the web, what browser were you using?
Chrome

### How severe is this issue?
MODERATE: should fix, but don't block next release

### Timestamp
2/11/2020 12:35:00

### In what screen/page did you find the bug?
Edit Animal in ADMIN

### What actually happened?
The page showed a red label in a textField momentarily (could not read it) and reported that the Animal was saved without any tag

### What part of the system needs work?
Admin

### Were you using a "native" or "web" app?
Web (using a web browser)

### What was the email (or phone number) for the account you were using?
enrique@agex.io

### What were you generally trying to do?
Remove the altTag

### What version of the app were you using?
2/11/2020

### Email Address
enrique@agex.io

# Affected Repositories
- [ ] agex.admin
- [ ] agex.api
- [ ] agex.common
- [ ] agex.service_workers
- [ ] agex.web
- [ ] android.herd
- [ ] ios.herd

**Comment by eharo2** [comment]
After the deployment of the API fix, the ADMIN sites shows a server-generated message and the textField shows the red label.     It may not need work.

**Comment by altemeier** [comment]
Per @eharo2's comment above
