### ISSUE TITLE
Add support to clear/remove (nullify) the starting and reserve prices in the sale wizard auction details

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#56]
# Report

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### What environment were you working in?
TEST

### What device were you using?
Android phone

### How severe is this issue?
LOW: would be nice to fix when we can

### Timestamp
2/11/2020 21:33:22

### In what screen/page did you find the bug?
Sale Auction Section

### What actually happened?
If I create a Sale with Reserve price, and later decide to change to Starting price w/o Reserve price, the Reserve price is not removed.   The same happens with Starting Price

### What part of the system needs work?
Herd

### Were you using a "native" or "web" app?
Native (downloaded from a store)

### What was the email (or phone number) for the account you were using?
enrique@agex.io

### What were you generally trying to do?
Remove the Starting or Reserve Price

### What version of the app were you using?
20701

### Email Address
enrique@agex.io

# Affected Repositories
- [x] agex.admin
- [x] agex.api
- [ ] agex.common
- [ ] agex.service_workers
- [ ] agex.web
- [x] android.herd
- [ ] ios.herd

**Comment by altemeier** [comment]
API: Fixed in https://github.com/agex-inc/agex.api/commit/7c06d9bae117c0b7cc8b2a05e0fdcc4e1aa76f0c

**Comment by joshpavlovich** [comment]
android.herd: Fixed in [android.herd/448](https://github.com/agex-inc/android.herd/issues/448) which is released and closed.
