### ISSUE TITLE
Handle invalid 10-digit phone numbers

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#6]
## Current Behavior
1.  Invalid US telephone numbers (10-digits, starting with 1) are accepted on signup and users are created with invalid phone numbers.

## Acceptance Criteria
1.  10-digit phone numbers are rejected as invalid by all clients as well as the API.

**Comment by eharo2** [comment]
[ios.herd #452](https://app.zenhub.com/workspaces/team-wide-5e39c8e0d7b280fe382c56e7/issues/agex-inc/ios.herd/452)

**Comment by altemeier** [comment]
Fixed in [agex.web #188](https://github.com/agex-inc/agex.web/pull/188)
