### ISSUE TITLE
User was able to click place a bid button without selecting an address

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#81]
# Report

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### What environment were you working in?
TEST

### What device were you using?
Multiple

### If you were using the web, what browser were you using?
chrome

### How severe is this issue?
LOW: would be nice to fix when we can

### Timestamp
2/13/2020 12:10:05

### What actually happened?
was able to click place a bid button without selecting an address; request fails and dialog closes without any feedback given to user indicating missing address was the problem

### What part of the system needs work?
Marketplace

### Were you using a "native" or "web" app?
Web (using a web browser)

### What was the email (or phone number) for the account you were using?
jjohnson@agex.io

### What were you generally trying to do?
place a bid

### Email Address
jjohnson@agex.io

# Affected Repositories
- [ ] agex.admin
- [ ] agex.api
- [ ] agex.common
- [ ] agex.service_workers
- [x] agex.web
- [ ] android.herd
- [ ] ios.herd

**Comment by jovjohnson** [comment]
What part of the system needs work? 

Web**

**Comment by altemeier** [comment]
_See_ #75
