### ISSUE TITLE
Visual tag sorting

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#83]
# Report

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### What environment were you working in?
TEST

### What device were you using?
Laptop/desktop computer

### If you were using the web, what browser were you using?
Chrome

### How severe is this issue?
LOW: would be nice to fix when we can

### Timestamp
2/13/2020 12:43:23

### In what screen/page did you find the bug?
Animals

### What actually happened?
The order in web/mobile apps is consistent as follows:
0001
0479
0483
Tag1.

The Admin shows a random order:
0479
TAG 1
0483
0001

It is not clear what the sorting criteria is (created/updated is not, considering the order of ingestion)

### What part of the system needs work?
Admin

### Were you using a "native" or "web" app?
Web (using a web browser)

### What was the email (or phone number) for the account you were using?
t1@agex.io (enrique)

### What version of the app were you using?
2/13/2020

### What actions did you take to try to make that happen?
Brand new account (t1@agex.io).   Added 4 animals in this order:
- Scanned AGEX Tag 0479
- Scanned AGEX Tag 0483
- Added AltTag 0001
- Added AltTag Tag1

### Email Address
enrique@agex.io

# Affected Repositories
- [x] agex.admin
- [ ] agex.api
- [ ] agex.common
- [ ] agex.service_workers
- [x] agex.web
- [ ] android.herd
- [ ] ios.herd

**Comment by eharo2** [comment]
![image.png](https://images.zenhubusercontent.com/5ae35ff84b5806bc2bd0f02d/79ce652f-5e45-4b2a-b0ae-48f1dce41236)
