### ISSUE TITLE
Validate manual AGEX tag input

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#85]
# Report

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### What environment were you working in?
TEST

### What device were you using?
Laptop/desktop computer

### If you were using the web, what browser were you using?
Chrome

### How severe is this issue?
MODERATE: should fix, but don't block next release

### Timestamp
2/13/2020 14:07:06

### In what screen/page did you find the bug?
Add Animal by typing Tag

### What actually happened?
The animal was added...       Removing 2 more digits (29990000000039FFFFFFFF) is detected as invalid)....

### What part of the system needs work?
Admin

### Were you using a "native" or "web" app?
Web (using a web browser)

### What was the email (or phone number) for the account you were using?
enrique@agex.io

### What were you generally trying to do?
Add an animal

### What version of the app were you using?
2/11/2020

### What actions did you take to try to make that happen?
Entered an invalid tag number in AGEX Tag (2999000000003942FFFFFFFF) - Removed the last 2 digits of the visual 299900000000394213FFFFFFFF.

### Email Address
enrique@agex.io

# Affected Repositories
- [x] agex.admin
- [x] agex.api
- [ ] agex.common
- [ ] agex.service_workers
- [ ] agex.web
- [ ] android.herd
- [ ] ios.herd

**Comment by eharo2** [comment]
**ADDITIONAL NOTES**:

- The form is also allowing to add an existing tag number in the platform
- It allows to add a 2nd tag w/o selecting the owner, keeping the previously selected owner sticky (not visible though)
